version: '3.7'

services:

  db:
    container_name: postgres_test
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: contrasena
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    ports:
      - 5432:5432
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: contrasena
      NAME: postgres_test
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge